### ISSUE TITLE
State changes tab for transactions

### ISSUE THREAD

**Issue by JamesHinshelwood** [otterscan/otterscan#1005]
It would be quite helpful to have a tab of state changes for a transaction, similar to Etherscan. For example:
https://etherscan.io/tx/0xeb5e0dc7eeb4226518e53bc536c83ecd1d6f20b66735ea2adf04e7d50ba337f9#statechange
![image](https://github.com/otterscan/otterscan/assets/11905377/c098c945-f703-43a5-a015-607f2f5336e1)

If I understand correctly, this would probably require a new API but not a new index, since its 'just' a transaction trace presented in a different way.

**Comment by wmitsuda** [comment]
sure, I guess so.

**Comment by sealer3** [comment]
Definitely agree. What would make this even better than Etherscan is the ability to trace the state changes to the calls that produced them. For example, it might not be clear what storage slot `0xabc123def456` in USDT is, but if right below we have an expandable list of the call(s) that wrote to that state, such as `transfer(my address, 100 tokens)` for the same address, it becomes clear that the storage slot `0xabc123def456` is the storage slot for your USDT balance.

**Comment by sealer3** [comment]
If we postpone my idea of associating the state changes with the calls that produce them, a straightforward implementation might simply be a more graphical display of [`trace_replayTransaction`](https://github.com/ledgerwatch/erigon/blob/devel/docs/readthedocs/source/rpc/index.rst#trace_replaytransaction) using `stateDiff` as the type of trace.

**Comment by JamesHinshelwood** [comment]
Ah, thanks for educating me about `trace_replayTransaction` - Yeah that looks perfect (and presumably exactly what Etherscan are using)

**Comment by sealer3** [comment]
I made a prototype that needs some styling help. I will make a draft PR once I clean up the code a bit.

![image](https://github.com/otterscan/otterscan/assets/125761775/0346b7d7-95c3-4135-ad48-0726b7c216ae)

**Comment by JamesHinshelwood** [comment]
If we had access to the `storageLayout` output of the compiled contract, we could probably display nice names for _some_ of the storage locations. I guess the only way to get that output though would be to re-compile the contracts locally, which might be somewhat overkill?

**Comment by JamesHinshelwood** [comment]
On the other hand, compiling contracts locally would make the contract source code a user sees in Otterscan properly trustless - Right now we're trusting Sourcify not to lie about the source code of a given contract, unless I've missed something?

**Comment by sealer3** [comment]
@JamesHinshelwood Both of your observations are correct. Sourcify's vision is for edge verification to become a reality. For Otterscan, that would mean recompiling and verifying contracts locally. Depending on the user's setup, this could be done from the back end and cached, e.g. if the user is the operator of the Otterscan instance.

I think we could just use `lib-sourcify` to handle recompilation and verification, so it might be possible to handle storage layout requests.

**Comment by JamesHinshelwood** [comment]
Thanks for clarifying, much appreciated.
