### ISSUE TITLE
Feature: Detect EIP-1167 minimal proxy contracts

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1029]
Some contracts are minimal proxy contracts, which we can identify simply by checking if the bytecode matches a known pattern. See the details here: https://eips.ethereum.org/EIPS/eip-1167

These contracts do a `delegatecall` on another contract, inheriting its logic. We can find this address by matching the pattern given in the EIP description. In the future, we may wish to show the source code of the contract that a proxy contract resolves to.

**Comment by wmitsuda** [comment]
that's already implemented in my indexer prototype! pretty easy :)

will leave this open until it is published.

**Comment by sealer3** [comment]
Completed with #1417

**Comment by sealer3** [comment]
Completed with #1417
