### ISSUE TITLE
UX unclearness

### ISSUE THREAD

**Issue by nebolax** [otterscan/otterscan#1094]
Hi, William! I've been exploring sepolia demo version of otterscan and would like to report some unclear UX that I faced.

1. On transaction view, the meaning of this progress bar (or what is it?) is not clear to me. I guess it may be the index of the transaction in the block? But it's not clear. Also I am curious: what info can it give to a viewer of the explorer, what can it be used for?
<img width="518" alt="image" src="https://github.com/otterscan/otterscan/assets/63492346/cf548a20-deee-4f93-b16e-e2b051bdde0b">

2. The meaning of these 2 progress bars is not clear 
<img width="847" alt="image" src="https://github.com/otterscan/otterscan/assets/63492346/e65fb96b-7d03-4388-97e2-34c781fb00a3">

3. The meaning of this [C] is also unclear for me
<img width="289" alt="image" src="https://github.com/otterscan/otterscan/assets/63492346/1c408e17-cf68-4f4e-8c13-52765086e8ed">

**Comment by wmitsuda** [comment]
hey! I apologize for the delay in the response.

1 - the 4/59 means it is the 4th tx inside the block, and the block has 59 txs. The bar is an attempt to give a quick visual explanation of the tx position inside the block (is the tx at the start of the block? at the end?)

2 - that give a visual explanation of how much % of the paid fees were burned by EIP-1559 mechanism and how much % was converted into validator fees.

3 - [C] means this address was identified as a contract (as opposed as an EOA; it has a code deployed to it). We may add more visual indicators in the future, suggestion are welcome to make all those UI elements work better.

**Comment by nebolax** [comment]
I saw your answer, but realized just now that I forgot to reply :) Thank, William, for the explanation. It's more clear now!

**Comment by wmitsuda** [comment]
you’re welcome!
