### ISSUE TITLE
Interface for executing view function calls for contracts with source code

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1105]
For contracts with source code, allow the view/pure functions of the contract ABI to be expanded, exposing input fields for executing them using `eth_call`.

For view/pure functions that have no arguments (such as getters), call the function automatically on expansion.

In the future we can cover transaction execution, which which use the same components. Also prepare for graphing the result of the view functions over a range of historical block numbers (see #1054).

**Comment by wmitsuda** [comment]
Assigning it to you :)
