### ISSUE TITLE
Reduce font size of smart contract source code

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1106]
The source code font size is markedly larger than the other text in the Otterscan interface. For example, the font size of the contract ABI is `0.875rem`, whereas the source code is `1rem`. It would be nice to make it smaller, maybe around `0.8rem`, and proportionally reduce the line height. That way, more of the contract source code is visible at a time.

**Comment by wmitsuda** [comment]
open to suggestions, post pics before/after and let's evaluate if it looks nicer.
