### ISSUE TITLE
Comments in contract source code create commented line numbers

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1107]
When there are comments in contract source code, the line numbers also get the commented style (green + italic):
![image](https://github.com/otterscan/otterscan/assets/125761775/ac8b9e22-f308-4498-b569-d4ae6169ac66)

The line numbers should all have the same style.

**Comment by wmitsuda** [comment]
I think this is a bug in the highlighter component itself

**Comment by wmitsuda** [comment]
fixed by migrating to Shiki
