### ISSUE TITLE
Migrate to ethers v6

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1184]
Umbrella issue just to remind us that we are doing that :)

**Comment by wmitsuda** [comment]
Assigned that to you @sealer3 .

Feel free to link any child PRs/discussions here, also to push smaller PRs that you think will make it easier to deal with given this is a big migration.

**Comment by sealer3** [comment]
Discussion related to the JSON-RPC formatter: https://github.com/ethers-io/ethers.js/discussions/4324

**Comment by sealer3** [comment]
I couldn't find a similar JSON-RPC formatter class in ethers v6, so one is included in the PR. I added full typing to it, so it should be easy to adapt to other ethers types and verify compatibility with them.

**Comment by jxom** [comment]
Feel free to take a look into viem.sh too ;)
