### ISSUE TITLE
Change standard return param label on "read contract"

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1191]
we are reusing the standard parameters UI component, which is good :)

but it was originally made to display function params, not return params, so if the return param is unnamed, it shows a standard "param_N" label, see sample image below.

<img width="611" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/18814861-b8d3-49f8-95ea-915901665622">

I suggest we improve the component by enabling a new prop to indicate it is showing returned data, and then use a "ret_N" text instead on this page.

**Comment by sealer3** [comment]
Work on this is complete, using ethers v6. Depends on #1189.

**Comment by wmitsuda** [comment]
merged the ethers v6 PR to unblock this one.
