### ISSUE TITLE
Support new indexer: fee recipient

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1348]
There is a new indexer for 2.2-ALPHA, given an address, returns a paginated view of all blocks it is the miner/block producer/fee recipient.

It works similar to the withdrawals search we've implemented in the past release, the method pair is: `ots2_getFeeRecipientCount/ots2_getFeeRecipientList` (name may change) and it is already available in our mainnet test server.

Le's implement a new tab in the address page, just after "Withdrawals".

Sample method call/returns:

```
curl -v -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "ots2_getFeeRecipientCount", "params": ["0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990"], "id":1}' <rpc-url>
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 385149
}
curl -v -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "ots2_getFeeRecipientList", "params": ["0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990", 385130, 5], "id":1}' <rpc-url>
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blocksSummary": {
      "0x1179c71": {
        "blockNumber": "0x1179c71",
        "timestamp": 1696995695
      },
      "0x1179c73": {
        "blockNumber": "0x1179c73",
        "timestamp": 1696995719
      },
      "0x1179c77": {
        "blockNumber": "0x1179c77",
        "timestamp": 1696995767
      },
      "0x1179c7f": {
        "blockNumber": "0x1179c7f",
        "timestamp": 1696995863
      },
      "0x1179c83": {
        "blockNumber": "0x1179c83",
        "timestamp": 1696995911
      }
    },
    "results": [
      {
        "blockNumber": "0x1179c71"
      },
      {
        "blockNumber": "0x1179c73"
      },
      {
        "blockNumber": "0x1179c77"
      },
      {
        "blockNumber": "0x1179c7f"
      },
      {
        "blockNumber": "0x1179c83"
      }
    ]
  }
}
```

For now, displaying the block number column is enough, in the meantime I may do some refactorings in the node side and think about which more data to add in the return json.

**Comment by sealer3** [comment]
@wmitsuda Is there anything else to add to this page?

**Comment by wmitsuda** [comment]
we may, but it seems ok for now. I want to work on e3 support before adding more stuff, so closing it.
