### ISSUE TITLE
Typing "/" to access the search bar is also adding the "/" character to the search

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1359]
There is a global "/" shortcut key to direct the focus to the search bar.

It used to work correctly, but I remember sometimes it was not only giving focus, but printing the "/" character in the search box implying I was probably not handling the keyboard event correctly.

But now I realized it is almost always printing the "/" character, so it is completely messed up :)

**Comment by wmitsuda** [comment]
Assigning to you @sealer3 , feel free to rework the event handling code completely if you feel it is necessary, I was not very inspired when I wrote it first time.

**Comment by sealer3** [comment]
Related: #444
