### ISSUE TITLE
Add prettier plugin for fixing imports

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1365]
It would be nice to have prettier automatically detect unused imports and merge and sort the others. The `prettier-plugin-organize-imports` plugin seems to work well.

- [x] Add the `prettier-plugin-organize-imports` prettier plugin
- [ ] Run prettier on all our source files
- [ ] Use GitHub Actions to run prettier on each PR and commit

**Comment by wmitsuda** [comment]
I support this idea. Better yet if we can add some check on github actions to check for unformatted code, I didn't bother to configure it so far because I was the only dev in the project and I always format the code using prettier on vscode before committing, but now it is seems to be useful.

**Comment by wmitsuda** [comment]
Adding to the task backlog

**Comment by wmitsuda** [comment]
Related: https://github.com/otterscan/otterscan/pull/1205

I didn't merge that yet because I was too lazy to check what needs to be changed.
