### ISSUE TITLE
UI improvements for the read contract proxy support

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1385]
This is a follow up of #1251 with some UI polishing:

- Rename "Contract as Proxy" tab to "Logic Contract".
- If the contract is detected as a proxy, let's add two new entries to the "Overview" tab, just  below "Contract Creator":
  - "Proxy type": in this case it's be "ERC1167 minimal proxy". There will be other when we implement it in the node side.
  - "Logic contract": the logic contract address with all UI decorations as always.

**Comment by sealer3** [comment]
Some proxy types allow the logic contract address to change, and it would be useful to show the previously used logic contracts. We should keep this in mind when we add support for other proxies.
