### ISSUE TITLE
Make the search bar responsive on tablet

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1398]
see the following picture taken from an ipad, I think we can make the search bar width flexible so it shrinks to fill the available space.

![IMG_0100](https://github.com/otterscan/otterscan/assets/28685/a24e350d-dcae-4552-9a47-90da9057c228)

**Comment by wmitsuda** [comment]
related to #1252

**Comment by sealer3** [comment]
The search bar actually does shrink as the zoom level increases, but so does the logo. Is the main point that the logo+main title shouldn't be obscured by the search bar? We could do this by putting the `shrink-0` class onto the logo's parent div.

**Comment by wmitsuda** [comment]
yes, I think the search bar should shrink in order to not overlap with the logo.
