### ISSUE TITLE
Make the search bar responsive on phone layout 

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1399]
I think we can add a line break after the logo and make the bar below the logo in this case to maximize horizontal space usage.

**Comment by wmitsuda** [comment]
![Screenshot_20231020-193240_Original](https://github.com/otterscan/otterscan/assets/28685/fff46b22-0d80-470e-9e73-2665e062871d)

**Comment by wmitsuda** [comment]
related: #1252

**Comment by sealer3** [comment]
It will look like this for small-width viewports:
![image](https://github.com/otterscan/otterscan/assets/125761775/8bc243f6-ae8c-4d89-b2fb-8604f3c9bd26)

**Comment by wmitsuda** [comment]
hm, I'd prefer the logo left-aligned with the hamburger menu in the same line, right-aligned.

and the search box taking the whole row then.

wdyt? too complicated? :)

**Comment by sealer3** [comment]
That's not a problem, but we'll have to render two SourcifyMenu components separately and show/hide them based on the viewport width:
![image](https://github.com/otterscan/otterscan/assets/125761775/15ff9aec-801f-46be-9dda-e5999658feef)

**Comment by wmitsuda** [comment]
I think that's ok, but add some vertical space between the rows plz

**Comment by sealer3** [comment]
Here it is with `space-y-1`. Lmk if you'd like more space:
![image](https://github.com/otterscan/otterscan/assets/125761775/0fbc2158-7eb6-4078-b94b-d5c3b15325fe)

**Comment by wmitsuda** [comment]
I'll merge this way, since the search bar is the main concern of this issue. There are other spacing-related stuff disturbing me too, I'll make it in another issue.
