### ISSUE TITLE
If a contract is verified by Sourcify, recover the method selector from the ABI

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1430]
This is another improvement request involving verified contracts.

If the contract is verified, we should recover the method selector from the verified ABI and use its method signature instead of decoding if from the 4bytes dictionary (which can have collisions).

See for example the following screenshot: we should display `swapETHForExactTokens` instead of `0xfb3bdb41` in the method column.

Also, as a subtle UI hint, let's use the same Sourcify-blue text color instead of black in this case.

<img width="1252" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/acc1bf4c-502f-4503-95aa-ed27279cf04a">

**Comment by sealer3** [comment]
Resolving this issue also resolves #333
