### ISSUE TITLE
Using debug namespace to use otterscan

### ISSUE THREAD

**Issue by kaliubuntu0206** [otterscan/otterscan#1444]
Hello,

How hard would it be to utilize debug namespace instead of ots namespace to use otterscan?

Thanks.

**Comment by wmitsuda** [comment]
a little :)

In the ots_ methods we cut off some verbose data we don't use, also now with ots2 indexers it would become impossible to directly get all info we want to expose in Otterscan.

it would be possible to develop some middleware that uses only debug/trace methods to extract data from a node and store it in some DB and then expose an ots_ compatible API on top of that, which is basically what blockscout, for example does.

but that approach is much slower which is the reason I started Otterscan. it was a trade off, hack Erigon, but we have more flexibility to get/produce all data we need.

**Comment by kaliubuntu0206** [comment]
Yes but it will be able to support more chains, I think we should build an indexer then

**Comment by wmitsuda** [comment]
out of curiosity, what are you building?

**Comment by kaliubuntu0206** [comment]
@wmitsuda Some indexer but I am facing some challenges regarding with the retrieval speed. With a single node it is limited with 1 blocks / sec nonetheless of the concurrency for the requests.

**Comment by wmitsuda** [comment]
feel free to ping me in private on twitter or discord if you need some advice and can share more details, I'm also interested in understanding issues people have with indexing in general.

**Comment by kaliubuntu0206** [comment]
@wmitsuda Yeah, I have just pinged you on discord
