### ISSUE TITLE
On iOS/iPadOS, the browser by default linkify everything it thinks it looks like a phone number

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1447]
see screenshot below from my iPad, it thinks the block number is a phone number.

I'm pretty sure there is some way to disable this apple-behavior globally in the page.

![image](https://github.com/otterscan/otterscan/assets/28685/adaee8b4-7284-49fd-bb8c-3711c95b4ae6)

**Comment by sealer3** [comment]
There is an iOS-specific meta tag called "format-detection" which we can use.
