### ISSUE TITLE
Parameter names never shown in trace

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1450]
@wmitsuda Is there a reason we hide parameter names in the trace? See here: https://github.com/otterscan/otterscan/blob/a4d5199b737e3fcd4ab945073ea83dc387a1ebae/src/execution/transaction/TraceInput.tsx#L88

**Comment by wmitsuda** [comment]
honestly I don't remember :)

**Comment by wmitsuda** [comment]
maybe we didn't had Sourcify integration at that time and 4bytes DB was the only source and the names in the DB may be really wrong.

**Comment by wmitsuda** [comment]
I think it should be fine if the contract is verified in Sourcify; if not I don't remember the edge cases, you may want to stress the possibilities.

**Comment by sealer3** [comment]
I agree, at minimum they should be included if the contract is verified.
