### ISSUE TITLE
Remove commify for raw integer values

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1461]
In my experience, I've found that using commify on raw uint256 values and other integer types is seldom useful.

![image](https://github.com/otterscan/otterscan/assets/125761775/1965cd0a-c71b-4ff2-9641-2f5592827ccc)

Even with digit grouping, in this example there are 7 groups of digits, so it's still not easy to tell exactly what the number is without counting the groups. I think most uses of integers in smart contracts has to do with the following:
1. Value amounts (commas seldom useful)
2. Timestamps (commas seldom useful)
3. Indexes, such as a token ID (might be useful)

The biggest drawback is that after commify is applied, it's not easy to copy this value elsewhere, like a calculator or script or an argument to a Read Function query, because of the commas.

So I think we should no longer commify the raw integer results in DecodeParamsTable and elsewhere.

**Comment by wmitsuda** [comment]
alright, you convinced me.

when I did it first, my difficulty was trying to visualize the number magnitude, i.e., thousands?, millions?

we may revisit this one if there is a better UI solution that doesn't get in a way of copy/pasting.
