### ISSUE TITLE
Decoded bytes value should not be truncated/ellipsis

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1500]
see mainnet tx: http://localhost:5173/tx/0x6d19a97f8ece4f746fbbb0b64ea4ba79500727ba95773cc3518de864184dd18a

the inputs[] should not be truncated, instead they should wrap and occupy all necessary lines so the user can see all bytes.

<img width="1355" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/d03acd6c-afb9-4028-ae44-2069bd85b20c">

**Comment by sealer3** [comment]
Related: #722
