### ISSUE TITLE
Add return value support to traces if the contract is verified

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1530]
This is a current limitation of our trace view, since we were relying only on 4bytes matching until recently. The 4bytes db has only signatures with parameters, not return value.

But if the contract is verified on Sourcify we have the entire ABI, hence we can reliably parse the return value.

I don't remember if the custom API Otterscan depends on already returns the return data, otherwise we'll need to add that in Erigon first.

**Comment by sealer3** [comment]
Even if the return values can't be decoded, they are really useful for debugging. But *with* return values is something few other block explorers do and would be even more helpful.

Glancing at the `otterscan_trace_transaction.go` file, it seems as easy as recording this `output` byte array parameter when a contract call exits: https://github.com/ledgerwatch/erigon/blob/4008115c424696a44110c3cb1a9bfbe280f30a4a/turbo/jsonrpc/otterscan_trace_transaction.go#L106C10-L106C10

**Comment by wmitsuda** [comment]
The backwards compatible change in the specs is here: https://github.com/otterscan/execution-apis/pull/1

And the proposed implementation is live in our test server (you can use an old tx until it is fully synced), commit: https://github.com/ledgerwatch/erigon/commit/c9617c41dea13883c4f7ed02bee6e81d9b297c3b

Once we validate this issue, I'll PR to erigon's devel branch since it is backwards compatible with E2.

**Comment by wmitsuda** [comment]
regarding the UI, I propose we do something similar to the input section, add an output section just below it with raw/decoded boxes.

**Comment by wmitsuda** [comment]
actually, I'm thinking if we could retrofit a raw tab into the "return value" control you did for the "read contract" (and user will get a raw view for free) and apply it to the trace input.
