### ISSUE TITLE
Use central Sourcify server by default

### ISSUE THREAD

**Issue by kuzdogan** [otterscan/otterscan#1533]
I recommend Otterscan instances use the central Sourcify server instead of the IPNS root to fetch contracts.

- The IPNS is not really stable and as it's getting larger in size, the IPFS instance is failing often
- It takes time for the IPNS to receive the updated contracts whereas it's instant with the server
- We are thinking about removing the filesystem structure altogether and with that likely the IPNS filesystem. We will pin individual files.
- Since we control the IPNS keys, it's basically the same thing as fetching from the Sourcify server or the IPNS in terms of decentralization.

**Comment by wmitsuda** [comment]
😭😭😭😭😭

@sealer3 let's do it for next release mid-December, plz. I'll also add some note in the release notes about privacy concerns on hitting Sourcify servers directly.

**Comment by kuzdogan** [comment]
Oh right, the privacy aspect was one downside I missed :( cc: @marcocastignoli

**Comment by sealer3** [comment]
@kuzdogan Will Sourcify eventually offer another way to download or sync verified contracts in bulk? Otterscan now has a config option to customize the Sourcify source, so an Otterscan server operator could also serve verified contracts by running a HTTP server compatible with the Sourcify API. This would eliminate the privacy risk.

**Comment by kuzdogan** [comment]
Yes in potentially two ways. 

As background, we are moving away from the current filesystem based on the source paths in the metadata.json. The problem is, they are actually not "paths" but "source-unit names", meaning they can be arbitrary strings. This makes it difficult to use them as file and path names and the current IPFS issues are caused by this.

We are considering using the keccak256 of sources as filenames to work around this. The metadata.json can be used to map the file names if needed. 

However, the assumption of this fs structure is still limiting because 
1. Not all Solidity contracts (e.g. pre 0.4.0) have metadata.json
2. Non-Solidity contracts don't have metadata.json
3. Some contracts are not fully reproducible with the metadata.json because of bugs

That's why we'll move to a DB-based structure, and have the filesystem on the side to serve the files on IPFS, especially for perfect matches that are retrievable in a fully decentralized way through IPFS (but need to be verified locally).

Open and easy access to verified contracts is a top priority for us. With this, it would be possible to get them:
1. From the DB dumps we produce regularly
2. The IPNS will still be there but with the aforementioned downsides

If there are other ways to do this I am happy to hear suggestions.
