### ISSUE TITLE
Option to show non-view functions that return values in Read Contract interface

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1579]
Some Uniswap functions modify blockchain state but actually are meant to be used in contract calls, such as those in the V3 Quoter (0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6) and V3 Price Oracle (0x885a58B151Cfa0A1Af467bd246022DE6EBcd2626).

We should add a toggle to the Read Contract interface that adds the functions which modify blockchain state but return a value.

**Comment by wmitsuda** [comment]
I like it, had similar needs in the past.
