### ISSUE TITLE
Add labeled address to page title

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1650]
An address with a label should have its label appear in the page title. This would make bookmarks and page history easier to manage in the browser.

**Comment by wmitsuda** [comment]
do you mean the textual representation of it? i.e. ENS name, hardcoded name, etc.?

**Comment by sealer3** [comment]
Yes, exactly. If it has a text label, any of those, it should appear somewhere in the page title once it is determined.

**Comment by wmitsuda** [comment]
ok, we can iterate over it.
