### ISSUE TITLE
Incorrect transaction fees calculation for merge block

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1658]
Even when accounting for incorrect block issuance (via #397), Otterscan reports transaction fees for the merge block that are far lower than the true value.

For the merge block `15537394`, Otterscan's `ots_getBlockDetails` -> `totalFees` reports transaction fees totaling to 9.601414427559942572 ETH, but the first transaction in the block, `0x5ad934ee3bf2f8938d8518a3b978e81f178eaa21824ee52fef83338f786e7b59`, paid 36.822159812482003764 ETH to the miner. Etherscan reports the fees for this block (not including burn) as 46.494902574979045804 ETH.

@wmitsuda

**Comment by wmitsuda** [comment]
here is the fix: https://github.com/ledgerwatch/erigon/commit/ab9554aabc08c3f8a4af17699bfabd2e9ff63bf4

I already updated our mainnet test servers.

Could you help me QA it please? once QA passed, I'll upstream to erigon's devel branch.

**Comment by sealer3** [comment]
The results are correct on all the blocks I've measured. Your code looks good.

**Comment by wmitsuda** [comment]
for the record, the existing bug should bring incorrect results due to overflow on every block with tx fee rewards > max(uint64), which is ~18 ETH, which is the case of the merge block.

**Comment by wmitsuda** [comment]
should be released in erigon >= 2.60
