### ISSUE TITLE
Dencun support

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1727]
This is an umbrella issue to track dencun-related data that we want to show in the UI.

Since our test servers are sepolia, let's wait dencun be activate on sepolia on Jan 30th to better evaluate what to do.

Dencun spec: https://eips.ethereum.org/EIPS/eip-7569

But for now, some interesting data I think we should display:

- EIP-4844 (https://eips.ethereum.org/EIPS/eip-4844) - that'll introduce tx type 3 (blob), we need to ensure it doesn't break UI and proper adjustments are done on info that doesn't make sense for that tx type on transaction details view.
- Also for 4844: block now has blob basefee/gas used/etc.

**Comment by sealer3** [comment]
Tracking ethers support for Dencun properties in blocks: https://github.com/ethers-io/ethers.js/issues/4570

Support for this and Dencun properties in transactions will appear in the next ethers minor release.
