### ISSUE TITLE
support for local testnets ?

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [otterscan/otterscan#1730]
Hi,

i found out about Otterscan and it seems really cool

However, i see it is supposed to run with Erigon

If we run a local testnet ( geth + lighthouse ), is it possible to use Otterscan with such a local setup ?

Answers appreciated!

P.S : i read issue  #430 , but i am not concerned with the mainnet or any other testnet, except a local testnet

**Comment by sealer3** [comment]
You can certainly run Otterscan with a local testnet instance, but Otterscan relies on special indexers and RPC calls that only Erigon currently supports, so running Erigon is a hard requirement.

You should be able to connect an Erigon node to your local testnet geth node and sync from the testnet geth node if having a geth node is a must.

In addition, you can create a devnet directly from Erigon. See our devnet command here that we use for testing: https://github.com/otterscan/otterscan/blob/develop/docs/testing.md#erigon-devnet Just note that the devnet runs a PoA variant of Ethereum that is pre-Shanghai.

**Comment by SyedMuhamadYasir** [comment]
@sealer3 ,

thanks for your descriptive answer!

**Comment by sealer3** [comment]
Also note that [foundry's `anvil` program](https://github.com/foundry-rs/foundry) has support for the Otterscan `ots` RPC namespace, so you can run Otterscan (with `experimental: false` in the config) using an anvil dev network.

**Comment by SyedMuhamadYasir** [comment]
Hi @sealer3 

so i might start running a PoS private testnet on Erigon now

OR i might integrate Erigon as a new Execution Layer client to an already existing network

so, as per our previous discussion, i should be able to run Otterscan, yes?

one last thing - is Otterscan purely an EL explorer? or can we use it for Consensus Layer too? (looking at stuff like deposits and validators etc)

**Comment by wmitsuda** [comment]
we support CL as well: https://docs.otterscan.io/install/beacon-chain/

**Comment by sealer3** [comment]
Yes, as long as your private testnet is compatible with Erigon, you should be able to run Otterscan.

**Comment by SyedMuhamadYasir** [comment]
thanks both! @wmitsuda and @sealer3 

i'll experiment and be in touch!
