### ISSUE TITLE
Add error boundary for catching unexpected errors

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1750]
we currently don't have any error boundary configured, so when some exception happens, things just mess up, UI becomes trash and needs to be manually refreshed, no feedback to the user that error may be logged in console, etc...

I think it's time to provide some better error handling by using error boundaries.

reference: https://legacy.reactjs.org/docs/error-boundaries.html

https://www.npmjs.com/package/react-error-boundary

we can iterate on the UI, but I was thinking about some global handler that catches any unexpected error and displays some overlay in the UI with it's content, maybe some instruction to open an issue for us, refresh the page, etc.

it'll be better than the current situation which is: page becomes blank, can't go back, user eventually refreshes the page.

**Comment by sealer3** [comment]
Great idea, I had the same idea for a long time.
