### ISSUE TITLE
Signal blob tx on transaction list results

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1768]
part of dencun support: https://github.com/otterscan/otterscan/issues/1727

we have a space before the transaction hash where we can display some decoration, currently being used only when the transaction fails to display a "revert" icon.

<img width="599" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/e98939fb-d5b7-420f-a355-2613a6dc291e">

I think we could use this same area to display an icon for blob transactions in order to make them easier to identify in tx result lists (criteria: tx type == 3).

I'd like to suggest this initial icon/color: https://fontawesome.com/icons/mound?f=classic&s=solid&pc=%23076ab6

with a tooltip of "Blob transaction"

open to discuss better icon/colors, let's see how it looks like.

**Comment by sealer3** [comment]
Here is what this color looks like:
![image](https://github.com/otterscan/otterscan/assets/125761775/199b737f-676c-4223-9e15-c143202d036c)

Personally, to separate blobs from the verified contract color, I'm considering a slightly different color, such as purple:
![image](https://github.com/otterscan/otterscan/assets/125761775/49caf409-b8b6-48e1-a4e9-e8845b098df0)

**Comment by wmitsuda** [comment]
hm, that icon doesn't look as good as I expected 😅

how do you feel about it?

**Comment by wmitsuda** [comment]
BTW, agree about your color comment

**Comment by wmitsuda** [comment]
what about using the soap icon?

https://fontawesome.com/icons/soap?f=classic&s=solid

<img width="105" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/240515b9-2ca7-416f-83db-dad99771706c">

**Comment by wmitsuda** [comment]
or simply the "O" icon

https://fontawesome.com/icons/o?f=classic&s=solid

**Comment by wmitsuda** [comment]
https://fontawesome.com/icons/disease?f=classic&s=solid

<img width="90" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/df587d48-bd29-422f-ad7e-fe5099e44f45">

**Comment by wmitsuda** [comment]
https://fontawesome.com/icons/cubes-stacked?f=classic&s=solid

<img width="100" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/a4156ae8-675c-4406-b215-e7319ec587e0">

**Comment by sealer3** [comment]
https://fontawesome.com/icons/splotch?f=classic&s=solid

I think `splotch` is a bit closer to the idea than `disease`:
![image](https://github.com/otterscan/otterscan/assets/125761775/69149ba5-38c3-4ab4-b594-1472ff603ae5)

**Comment by wmitsuda** [comment]
I'm testing the PR and taking a look at the other icons against sepolia tx list, and so far I think splotch looks the best.

**Comment by wmitsuda** [comment]
about the color, the purple one isn't "clicking" on me, I think we should try something closer to the blob fish which is the unofficial meme.

let me try some `rose` variants here.

![image](https://github.com/otterscan/otterscan/assets/28685/62d79aaf-143f-4e3a-bb10-51c5140b32f3)

**Comment by wmitsuda** [comment]
`rose-400`, wdyt?

<img width="822" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/e6109a51-15ff-42bb-ad63-b85a30be7dbb">

**Comment by sealer3** [comment]
I think the rose color is a bit too red. Would `pink-400` be a good compromise? Official sources say blobfish are "pale pink" or "pinkish gray" anyway; the photo above is miscolored, unless that's part of the meme.

![image](https://github.com/otterscan/otterscan/assets/125761775/e914f2dc-b118-4e44-b1c2-43199e21622c)

**Comment by wmitsuda** [comment]
I prefer the rose-400, IMHO it looks better being kind of red-ish than pink-ish. TBH, pale pink looks like rose to me :)

I tried lighter versions of rose to reduce the red-effect, but it didn't look great, so -400 seemed ok.
