### ISSUE TITLE
Enable fast page-stepping on block pages

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1784]
You can step quickly through blocks using the page controls by clicking rapidly at, for instance, `/block/5218604/txs`. On some other pages, like `/block/5218604`, the application makes you wait for the block details to load before letting you click a navigation button again.

* [x] Allow fast page-stepping in the navigation on the `/block/<number>` page
* [x] Investigate why fast page-stepping works on some pages and not others
* [x] Find other places where fast page-stepping would be a UX improvement

**Comment by wmitsuda** [comment]
totally up for it if you can figure out how to optimize/reorg the routing/rendering waterfall :)

**Comment by sealer3** [comment]
There were not any other pages I could find where this change would be easy to do. It would be nice to do for nonce/transaction position stepping, but these currently require the transaction to load first. We can reopen this in the future as needed.
