### ISSUE TITLE
Link to beacon block page using `parentBeaconBlockRoot`

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1855]
Part of #1727. The parent beacon block root on a block page should be a link to a beacon block page. The beacon block can be accessed via hash using the same beacon API as the one that gets a slot by number, so we can either redirect a beacon block (by hash) to its corresponding slot number page once it is found or accept routing to a beacon block page by hash in addition to slot number.

**Comment by wmitsuda** [comment]
not thaaaaat priority, but we should do it for the sake of completeness.
