### ISSUE TITLE
Allow decoding of contracts for ephemeral chains, i.e. Otterscan + Anvil instance

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1870]
This is something that reached me by DM, and I think it would be interesting to have, but I don't know the best approach to make it, so open to discussions.

The use case is: user runs an ephemeral chain in Anvil, points Otterscan to it, wants to trace/decode calls, but since the chain is ephemeral there is no Sourcify endpoint to serve the ABIs.

**Comment by sealer3** [comment]
A user submitted to me documentation for setting up and running a local Sourcify instance for use with Otterscan. A first step might be publishing the guide for doing this. Alternatively, you can run a simple HTTP server that has the same Sourcify directory structure. Both methods involve changing the `sourcifySource` in the Otterscan config.

**Comment by wmitsuda** [comment]
related: https://github.com/otterscan/otterscan/issues/1939

**Comment by wmitsuda** [comment]
I think we can close this one for now given the instructions for local sourcify
