### ISSUE TITLE
Solidity code display puts line breaks between lines

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1886]
E.g., copying the first lines of a verified Uniswap router contract:
```solidity
pragma solidity =0.6.6;



interface IUniswapV2Factory {

    event PairCreated(address indexed token0, address indexed token1, address pair, uint);



    function feeTo() external view returns (address);

    function feeToSetter() external view returns (address);



```

Line breaks should not be doubled.

**Comment by wmitsuda** [comment]
not sure if I got it, does the original verified code have double line breaks?

**Comment by sealer3** [comment]
No it doesn't. Try highlighting and copying the source code from this address to the clipboard and paste it somewhere else: https://sepolia.otterscan.io/address/0xc4ADf4C01DC93Fc54a7d1Fa615B9f1Df56D67132/contract

**Comment by wmitsuda** [comment]
some issue with the highlighter component we are using then?

**Comment by sealer3** [comment]
Yes, I think so. Otterscan has had this issue for at least 1 year. Not being able to copy contracts correctly is not good.

**Comment by wmitsuda** [comment]
regardless of this issue, do you think copy/pasting from the UI is an important feature? because some contracts are spread over multiple files.


if that’s the case, wouldn’t it be more useful to provide a quick way for the user to download the entire set?

**Comment by sealer3** [comment]
Yes, I think it's quite important. But I would say that it's like how being able to copy code directly from the GitHub web UI is useful. You can always run `git clone`, which you're right, we don't have in Otterscan yet, but sometimes you just want to copy a single function or interface.

**Comment by wmitsuda** [comment]
fixed by migrating to Shiki
