### ISSUE TITLE
Support Ecotone fork transaction fees

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1956]
Otterscan does not recognize the L1 security fee for transaction fees on chains following the OP Stack following the Ecotone hard fork.

Not all the fields exist anymore, so Otterscan does not incorporate the L1 security fee for Ecotone transactions:
![image](https://github.com/otterscan/otterscan/assets/125761775/2480e49e-093e-4be6-8328-53b8299ec8a5)

**Comment by wmitsuda** [comment]
can you point me to some summary of the changes? (just being lazy to search the specs)

**Comment by sealer3** [comment]
https://docs.optimism.io/builders/notices/ecotone-changes

> The proposed Ecotone upgrade to the OP Stack and OP Mainnet changes the formula for estimating the L1 Data Fee component of the OP Stack Transaction Fee in preparation for the introduction of EIP-4844 support.

**Comment by wmitsuda** [comment]
Thanks, we should definitely do that
