### ISSUE TITLE
Add broadcast transaction feature

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1965]
Other block explorers let you broadcast a signed transaction from the explorer interface. It would be useful to have this in Otterscan, too.

**Comment by wmitsuda** [comment]
you mean, implementing the "write contract" part? yes, we'll do it of course :)

it just occurred to me that we should do the address tagging/labeling first, that's why I've asked for that prototype.

**Comment by wmitsuda** [comment]
TBH, I never used such feature in my life.

Looking at Etherscan I can find it. But is there a real use case for it? And it is now 2024, can't the original target audience just use foundry, for example? (or can say they **will** indeed prefer to use foundry)

**Comment by sealer3** [comment]
The use is for when the transaction signer does not have a (direct) connection to an Ethereum node or provider. Some account abstraction implementations, offline wallets, and new transaction type testing require the feature because they output signed transactions. Including it in the block explorer is useful because you will immediately want to view the transaction once you've sent it. If the block explorer doesn't have one available, you have to set something up yourself, such as sending an RPC request manually.

For example, you can send blob transactions which your wallet doesn't support by broadcasting a raw signed blob transaction.

**Comment by wmitsuda** [comment]
I'm still doubtful about this one, because if you are an ots user, you indeed have access to a working node.

and I think I would prefer try to use forge in this case instead of the UI because it is more practical

**Comment by sealer3** [comment]
Otterscan users of course run their own nodes, but that doesn't mean the application or wallet in question has direct access to one - think of offline wallets. This feature would make it convenient for Otterscan users to do this with their own node. Another use case I can think of is for broadcasting replacement transactions you have manually signed because your primary wallet doesn't support transaction replacement.

You could of course manually construct a `curl` request to your own node's RPC server to broadcast a transaction, or use forge's `cast` command to do it. Neither is a really good user experience. It is much nicer to do it from the block explorer if you need this feature rather than going to the command line. Mobile users with signed transactions would not be able to use forge.

I'm curious if @JesseBusman has any extra context to motivate the inclusion of the feature.

**Comment by JesseBusman** [comment]
Don't really have anything extra to add. I've signed transactions offline and then broadcast the raw signed transaction at https://etherscan.io/pushTx. I don't think this is unheard of at all; in my opinion holding or using the private keys to a lot of crypto on an online computer is super risky.

**Comment by wmitsuda** [comment]
ok, if others think it is useful, we can do it.

not that high priority though, but we can do it. also open to accept a PR if anyone wants to accelerate its inclusion.
