### ISSUE TITLE
Add support for ABI guessing

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#2018]
we should take a look at: https://github.com/shazow/whatsabi

it could be useful for non-verified contracts.

it looks like it can work totally standalone, just providing the contract code, but we should be careful and take a deeper look at their code to make sure we are not introducing any external dependencies/calls.

**Comment by wmitsuda** [comment]
that is an interesting one to take a look @sealer3

**Comment by sealer3** [comment]
Cool idea. We can use our own 4bytes lookups instead of the external service.

**Comment by sealer3** [comment]
Whatsabi only has ethers listed as a dependency, and indeed we can just ask whatsabi for the function selectors and do the lookups ourselves.

I have a basic version working which needs polishing. The function selector does not include the return value types in its hash, so 4bytes does not have the return values, and the Read Contract interface can't decode return values. So this is one usability issue.
