### ISSUE TITLE
Integrate May monthly Forge release into integration tests

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#2063]
- [x] When Forge posts its May monthly nightly release, update the E2E anvil workflow using the new release, which includes https://github.com/foundry-rs/foundry/pull/7807 and fixes the Anvil E2E test failures

**Comment by wmitsuda** [comment]
it looks like it is breaking again, so reopening.

**Comment by wmitsuda** [comment]
hm, may be not? some broke yesterday, but today it seems to be working.
