### ISSUE TITLE
Feature Request - expose 'assetsURLPrefix' as an environmental variable for Docker

### ISSUE THREAD

**Issue by dreadedhamish** [otterscan/otterscan#2074]
Per the title - it would be great to expose this parameter for users of Docker

**Comment by sealer3** [comment]
We should also expose an option to set the entire Otterscan config JSON for Docker users.

**Comment by dreadedhamish** [comment]
> We should also expose an option to set the entire Otterscan config JSON for Docker users.

Yes now that I understand the issue more I'd like all the options exposed. There are 2 places this should be enabled:
1. exposing VITE_CONFIG_JSON so it can be set as as environmental variable, and
2. not overwriting usr/share/nginx/html/config.json on startup
WIth both a user could choose whether to pass variables on startup or mount the config folder.
