### ISSUE TITLE
Docker build (arm/64) failing constantly

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#2227]
For some unknown reason our docker build keeps failing during the arm/64 build.

I initially used to use the multiarch-style build, it was already failing sometimes. It was already clear at this point that for some reason the `npm ci` in the arm build was taking ages and eventually timeouting the entire build.

Then, in an attempt to debug the issue, I tried to separate builds and merge the final image into multiarch, that only showed clearly that happening in the separate arm/64 job.

No clue about why it is happening, maybe something in the hosted github actions env? But I couldn't find any other report about it.

**Comment by wmitsuda** [comment]
Just reverted all debug stuff I did months ago: https://github.com/otterscan/otterscan/pull/2228

**Comment by wmitsuda** [comment]
@sealer3 maybe you have some clue or better insight?

**Comment by sealer3** [comment]
The CI logs show that this is always due to some kind of networking error when running the `npm ci` command.

**Comment by wmitsuda** [comment]
I think I may have fixed it (or workaround it because I don't think forcing a platform in the dockerfile is a good solution): https://github.com/otterscan/otterscan/pull/2229

inspired by: https://gist.github.com/ijpatricio/fe3ea4029743a209a70358181144a267

let's leave this opened for a while.

**Comment by wmitsuda** [comment]
Closing, as all recent buildings were successful, I think the workaround worked.
