### ISSUE TITLE
Check timestamp of token price feeds

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#2241]
The ETH/USD Chainlink price oracle is probably not going to go out of operation for a long time. Other token price oracles might not last as long, such as when someone stops paying for it:
![image](https://github.com/otterscan/otterscan/assets/125761775/a22abf58-db7a-4cce-b83f-050b664f65bb)

For token prices, let's check the last updated timestamp and, if it's very out of date, ignore the result and use the fallback oracles instead.

**Comment by wmitsuda** [comment]
did you find any example on mainnet?

**Comment by sealer3** [comment]
Here is an example. The NMR price feed hasn't been updated in 301 days. So this recent transfer: 0x666a2c4bd004899c09b5762a89415c5d0c828aabce06510a62c66d38c1fde5af

should have value $17.26 (current price) * 222 = $3831.72. But Otterscan is calculating using an outdated price ($11.3086) from August 25, 2023 and showing the wrong value:
![image](https://github.com/otterscan/otterscan/assets/125761775/7632f7eb-5f84-4f36-8c44-dc86ae8721fb)

**Comment by wmitsuda** [comment]
ok, agree. we should only use "fresh" quotes.
