### ISSUE TITLE
Error: network is not available yet

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#2262]
```
/

Error: network is not available yet (code=NETWORK_ERROR, version=6.13.1)
```

I've seen this on page load, usually over a spotty connection. I think this might happen when the page loads before a connection is made to the Erigon node. The error was probably introduced in #2225 and originates from https://github.com/otterscan/otterscan/blob/3adcc62c4eedc56f812fab5ca4b85e3c5fd4b595/src/useChainInfo.ts#L19. To fix it, we should call `const network = await runtime.provider!.getNetwork()` to get the network instead of accessing it directly.

**Comment by wmitsuda** [comment]
thanks! and I just realized I forgot to fix the TODO, now it is guaranteed the fields in runtime are filled or an error is thrown, so I can get rid of lots of `?.` questionable assertions in the code. will do another PR to clean those up.
