### ISSUE TITLE
QR scanner banner starts halfway across the page

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#2268]
![image](https://github.com/otterscan/otterscan/assets/125761775/19bcc522-8742-4971-9d33-92107bfaebe0)

**Comment by wmitsuda** [comment]
must have had a regression sometime in the past.

also, I just noticed it is inverting camera colors on dark mode, could you take a look at that as well? :)

**Comment by sealer3** [comment]
Yes, fortunately there is a "no dark mode" class name we can use.
