### ISSUE TITLE
Sepolia

### ISSUE THREAD

**Issue by ErnestoLara** [otterscan/otterscan#2433]
dirección/0xFF69530A8fB7b3948B20f440638E445972b8437A

NotFoundError: No se pudo ejecutar 'removeChild' en 'Node': el nodo que se va a eliminar no es un hijo de este nodo.

Error: No se pudo ejecutar 'removeChild' en 'Nodo': El nodo que se va a eliminar no es un hijo de este nodo.
    en control de calidad (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:26089)
    en br (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27379)
    en e4 (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27839)
    en br (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27529)
    en e4 (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27839)
    en br (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27529)
    en e4 (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27642)
    en br (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27529)
    en e4 (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:30579)
    en br (https://sepolia.otterscan.io/assets/index-Ds7auaZQ.js:41:27529)`

**Comment by wmitsuda** [comment]
hi, could you provide more details? not sure how to reproduce it
