### ISSUE TITLE
How to get WhatsAbi working?

### ISSUE THREAD

**Issue by akshatmittal** [otterscan/otterscan#2441]
Context: Working on running [otterscan for local anvil instance](https://github.com/0xMetacrypt/otterscan-devnet) but running into issues.

I'm unable to get WhatsAbi to show _anywhere_, not on Contract pages, not on transactions and I'm not sure why. Tried looking at env variables but there doesn't seem to be an enable/disable flag for it.

WhatsAbi would be very useful since sourcify no longer works (ipns 500s on gateways, and central repo is errors on CORS) and loading selectors from 4byte is a great way to get _some_ idea on the transaction and traces page.

**Comment by sealer3** [comment]
Whatsabi should show on the Contract tab like this:

![image](https://github.com/user-attachments/assets/b9911bbc-2f83-4602-8b31-8df9a15d5db2)

There isn't a flag for it, and you will have to have 4bytes signatures downloaded and accessible for Otterscan to be able to recognize function signatures (I did not have this set up in the above image).

Sourcify currently is not returning the `access-control-allow-origin: *` header when the files don't exist, so you will only get these CORS errors for contracts that aren't verified. If you want to verify your contracts with Sourcify for a local anvil instance, consider running Sourcify locally: https://docs.otterscan.io/contract-verification/self-hosted-sourcify/

**Comment by akshatmittal** [comment]
I'm not even seeing the ABI section here.

![image](https://github.com/user-attachments/assets/963fc3d5-2e65-4367-90c5-e72c4b8d66f1)

> have 4bytes signatures downloaded and accessible for Otterscan

How can I do that? I was assuming it loads them directly from the 4byte directory using the autoloader.

> Sourcify

Got it, and not a problem in this case! If WhatsABI is able to guess the selectors, that actually does solve my use case.

**Comment by sealer3** [comment]
I'm not able to reproduce the issue. Would you please confirm that you are running the latest version of Otterscan? If you are able to change the theme (light, dark, system) in the top-right menu in Otterscan (see https://github.com/otterscan/otterscan/releases/tag/v2.6.0), then you are running a version that is recent enough.

In terms of versions, this is at least v2.6.0, or the main or develop branch.

**Comment by akshatmittal** [comment]
Yes, this is built directly from `develop`. ([Build Action](https://github.com/0xMetacrypt/otterscan-devnet/blob/main/.github/workflows/deploy.yml))

**Comment by sealer3** [comment]
I've identified a separate bug in Anvil having to do with the format of the logs object it returns for transactions - in some cases, this will cause the address transaction list to fail to load. But performing those same steps on a local Otterscan `develop` build gives me the expected result:

![image](https://github.com/user-attachments/assets/21aaa921-4b6e-49e5-98ef-e4ca33eb3d22)

**Comment by akshatmittal** [comment]
Okay, figured out the issue.

So turns out, if `assetsURLPrefix` isn't specified, it will _never_ show that section. Just adding a random `assetsURLPrefix` (even when totally wrong) shows the "unknown functions" section.

I'm guessing that somewhere in the code it's checking if `assetsURLPrefix` is set and only then enabling this section and disabling it completely otherwise (which isn't the right behaviour, the `assetsURLPrefix` should only be required to fetch function names not to load the signatures)

(Pushing a patch to my public deployment to verify this theory)

**Comment by akshatmittal** [comment]
Yep, unknown selectors now show up here: https://otterscan-devnet.metacrypt.org/address/0x0000000000FFe8B47B3e2130213B802212439497/contract

Also, related question, why not directly load signatures from the 4byte API instead of relying on the assets index? (Example: https://www.4byte.directory/api/v1/signatures/?hex_signature=0x64e03087&format=json, possibly configure as fallback in the autoloader)

**Comment by sealer3** [comment]
> why not directly load signatures from the 4byte API instead of relying on the assets index?

I think this partly has to do with Otterscan's design values. Everything on Otterscan's "backend" can be served entirely locally, which comes with better speed, privacy, availability, and customizability.

Serving from the 4byte.directory API is definitely something we could include as an option. It would probably make setup easier when you want an Otterscan instance up quickly.

**Comment by akshatmittal** [comment]
Yeah I agree, I actually quite like those value as well but makes hosting a public instance harder and often out-of-date (see the instance I'm hosting for example).

Possibly include a `noAccess`/`privacyFriendly` sort of flag to enable/disable external API calls? Everything in the current `otterscan-assets` can be loaded externally via APIs or via GitHub directly, which - imo - is super useful.

**Comment by wmitsuda** [comment]
I see... I think we could make ots more flexible in order to better support scenarios like anvil forking where not all datasources are available in an offline way.

something unrelated to this issue, but since you mentioned anvil forking, I think another improvement could be to allow sourcify lookup in the parent chain for contracts before the fork block, since the forked chain has another chain id.

**Comment by akshatmittal** [comment]
@wmitsuda Yep, most certainly. I actually ended up setting that up here https://github.com/0xMetacrypt/otterscan-devnet and since I mostly fork local anvil with chain ID 1, sourcify just works. That said, it's not obvious to me how to expose the forked chain ID if anvil is on chain ID 31337.

Everything ended up working fine as I made a couple changes to the setup!
