### ISSUE TITLE
`OperationType` EOFCREATE

### ISSUE THREAD

**Issue by emhane** [otterscan/otterscan#2457]
Add `OperationType` EOFCREATE

https://github.com/otterscan/otterscan/blob/c7b81575985ed57c723b84b2b8c5ff6c6e8c5131/src/types.ts#L91-L96

**Comment by wmitsuda** [comment]
for reference: https://eips.ethereum.org/EIPS/eip-7620

**Comment by sealer3** [comment]
Sure.

**Comment by emhane** [comment]
plans on doing a patch release @wmitsuda ?

**Comment by wmitsuda** [comment]
> plans on doing a patch release @wmitsuda ?

I was not planning to, but I may do it if you need it. Just curious, is it something reth-related? I thought Otterscan API was not working on reth yet.

**Comment by wmitsuda** [comment]
also note that if you need a docker build and don't mind using `develop` builds, every commit automatically pushes a `develop` image tag on dockerhub.

**Comment by emhane** [comment]
yepp it's for alloy, main dep of reth https://github.com/alloy-rs/alloy/issues/1288

**Comment by wmitsuda** [comment]
pushed tag 2.6.1 cherry picking this PR: https://github.com/otterscan/otterscan/releases/tag/v2.6.1
