### ISSUE TITLE
Properly handle missed slots

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#2498]
Currently we display an error-ish page when:

- Slot is missed
- CL doesn't have that data (because node is pruned, didn't backfill, etc.)

<img width="417" alt="image" src="https://github.com/user-attachments/assets/2bb41927-74a2-493e-8b93-95d6c3a6a46e">

I think we can now try to search for a more elegant solution, if it exists and it is not expensive (i.e. have to do a lot of networks calls to CL API), in order to detect the correct scenario and display a nicer page to the user:

- If the slot is missed, we could display the standard slot page linked to the expected validator who missed it and blank fields like we do in the epoch page.
- If we could reliably CL doesn't have data, we could explain to the user he needs to enabled archive data in CL, backfill, etc...

**Comment by wmitsuda** [comment]
I think we could target Caplin and LH for our tests and expect them to handle HTTP errors properly in order to have reliable responses, i.e. HTTP 404 vs 500 when slot is missed, and other similar situations.

**Comment by wmitsuda** [comment]
one situation I'm noticing is that LH is returning HTTP 500 to some slots in pectra devnet-3 because of some internal error, but we assume it as a "missed slot", for example.

**Comment by sealer3** [comment]
We can reliably determine that a slot `s` was missed if the parent hash of a slot following `s` is of a beacon block which came before `s`.

We definitely should handle HTTP 500 responses as errors.
