### ISSUE TITLE
Trim fast gas price to 3 decimal places

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#2555]
I think displaying the gas price with 9 decimals is excessive, especially considering that it's just an estimate. We should trim it to 3 significant figures or 3 decimal places (whichever gives more decimal places).

Relevant line is here: https://github.com/otterscan/otterscan/blob/3e88b2771eb5cc2c1625e47a9548e9e53bf28fa8/src/PriceBox.tsx#L117

**Comment by 0xgun** [comment]
@sealer3  I would like work on this

**Comment by sealer3** [comment]
> @sealer3 I would like work on this

Thank you. Please be sure to write the logic to compute the number of decimals in a new function in `formatter.ts` and keep `formatValue`.

Here are some cases (wrapped with `formatValue`):
- `4289524854385` formatted as `4,289.525`
- `4512` formatted as `0.00000451`
- `1` formatted as `0.000000001`

**Comment by wmitsuda** [comment]
assigning it to you @0xgun

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
