### ISSUE TITLE
Remote Erigon node unresponsive when searching in Otterscan

### ISSUE THREAD

**Issue by lgaroche** [otterscan/otterscan#383]
Context: Trying to deploy Otterscan on a DappNode, where Erigon is an official package that can't be easily patched. The [Otterscan dappnode package](https://github.com/lgaroche/DAppNodePackage-otterscan/tree/bump) we're trying to build uses a patched rpcdaemon that connects to Erigon using the private API.

As soon as an address or contract search is started in Otterscan, the Erigon node prints "context canceled" errors and stops responding (and syncing). The search never completes, Erigon needs to be restarted and rpcdaemon stopped. 
Note: transaction or block searches are working fine

```
[INFO] [09-21|16:19:12.095] RPC Daemon notified of new headers       from=15582888 to=15582889 header sending=12.715µs log sending=320ns
[INFO] [09-21|16:19:12.095] [1/15 Headers] Waiting for Beacon Chain... 
[INFO] [09-21|16:19:13.562] [txpool] stat                            block=15582889 pending=109 baseFee=30000 queued=30000 alloc=3.4GB sys=5.6GB
[WARN] [09-21|16:19:25.048] Served                                   conn=172.33.0.24:60114 method=engine_exchangeTransitionConfigurationV1 reqid=1416 t=1.000178725s err="context canceled"
[WARN] [09-21|16:19:54.070] Served                                   conn=172.33.0.24:33220 method=engine_exchangeTransitionConfigurationV1 reqid=1420 t=998.015389ms err="context canceled"
[WARN] [09-21|16:19:58.050] Served                                   conn=172.33.0.24:33388 method=engine_exchangeTransitionConfigurationV1 reqid=1421 t=1.000272955s err="context canceled"
[WARN] [09-21|16:20:11.071] Served                                   conn=172.33.0.24:33916 method=engine_exchangeTransitionConfigurationV1 reqid=1424 t=1.000539187s err="context canceled"
[INFO] [09-21|16:20:13.164] [p2p] GoodPeers                          eth66=33
[WARN] [09-21|16:20:21.723] Served                                   conn=172.33.0.24:60006 method=eth_getBlockByNumber reqid=1414 t=1m0.000308059s err="context canceled"
```

Is using rpcdaemon on a remote Erigon node supported with Otterscan?

**Comment by wmitsuda** [comment]
it should be, I run rpcdaemon standalone sometimes, although just locally and not connecting to erigon, but just to the datadir, for testing purposes.

Are you trying searching for a specific address, or looking for tx inside a block number also triggers this issue?

**Comment by lgaroche** [comment]
Have you tried without sharing the datadir? See [this mode](https://github.com/ledgerwatch/erigon/tree/devel/cmd/rpcdaemon#running-remotely)
The issue only triggers when opening an account (I can browse between blocks and transactions just fine)

I managed to manually configure the containers so that the rpcdaemon uses the shared datadir and the issue stops occurring, although it's currently not possible to create a dappnode package that uses volumes from another package, I'm looking into the possibility to allow this on the dappnode side.

**Comment by wmitsuda** [comment]
hey, sorry for the delay, I haven't tried it yet, because I know it is slower indeed, and I saw some msgs on erigon discord saying that the performance in the alphas got much worse (but I didn't measure it).

So since the performance on address search is already bad (and I'm aware of that), it should add to the slower performance of remote rpcdaemon (without datadir sharing).

OTOH, I should dedicate more time to dappnode, I was waiting for the merge to happen to get deeper on that.

**Comment by lgaroche** [comment]
Hi, looks like this has been resolved, the latest Dappnode Otterscan package works out of the box with the latest Erigon! :)
