### ISSUE TITLE
Post-merge block reward amounts incorrect

### ISSUE THREAD

**Issue by mattdf** [otterscan/otterscan#397]
Since the Paris upgrade, the 2 ETH block reward is gone and the only reward validators get is the miner tips from 1559.

You just need to remove the 2 ETH constant value and subtract the burnt fees from the total fees.

Etherscan vs otterscan screenshots for reference.

![Screenshot from 2022-10-05 02-22-35](https://user-images.githubusercontent.com/11067114/193954058-e3589cb2-debc-4463-b8fa-bb5db6b2bd45.png)
![Screenshot from 2022-10-05 02-22-13](https://user-images.githubusercontent.com/11067114/193954062-353c5a6a-b88c-4a06-a6a0-1031574e3646.png)

**Comment by wmitsuda** [comment]
Hey, sorry for the delay, was at devcon.

I've noticed that too, I should take a look at it next week after I cut next release.

**Comment by sealer3** [comment]
This issue stems from Otterscan fetching block rewards from the PoW ethash `AccumulateRewards` consensus function in Erigon.

Here's a PR into ots2-alpha4 that solves the problem by checking for the merge into PoS in the same way as the trace filter API, which also calculates block rewards: https://github.com/ledgerwatch/erigon/pull/9113

**Comment by wmitsuda** [comment]
Should be fixed in Erigon >= 2.60 (to be released soon) or in the current Erigon`devel` branch.
