### ISSUE TITLE
Limit file watcher directories

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#556]
Running `npm run start` with all the submodules cloned, I am hitting the limit for file watchers because of all the 4bytes files:

```
Error: ENOSPC: System limit for number of file watchers reached, watch '/otterscan/4bytes/signatures/0da45188'
```

Is there a way to disable watching the assets directories? Or run in release mode maybe?

**Comment by wmitsuda** [comment]
yeap, unless you are working on the code, you should use the production-optimize build (either the published docker image or the result of `npm run build` which graps the production app in `/dist`.

The Dockerfile also gives you a hint of how all those submodules are assembled.

I don't remember if I did something in my installation to overcome that issue, but I think the current way of running it in dev mode is not optimal.

**Comment by sealer3** [comment]
I was able to overcome the file limit by making another directory with the external assets outside the otterscan directory and symlinking the correct asset folders to that one. I think the file watcher doesn't follow symlinks. It was something like

```
cd ..
mv otterscan/4bytes .
mkdir other_assets
cd other_assets/
ln -s ../4bytes/signatures signatures
ln -s ../otterscan/chains/_data/chains chains
ln -s ../otterscan/topic0/with_parameter_names topic0
mkdir assets
ln -s ../../otterscan/trustwallet/blockchains/ethereum/assets assets/1
```

And then I would serve the `other_assets` directory at the other assets URL using a local HTTP server. This probably isn't optimal either since you are moving the `4bytes` submodule directory, but it works.
