### ISSUE TITLE
Sourcify IPFS provider privacy

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#615]
By default, Otterscan leaks your address lookups to the IPFS provider (currently ipfs.io) to do Sourcify lookups. It would be nice to include as a config option a custom Sourcify endpoint and a way to disable resolving Sourcify sources at all. And also to include documentation for how to clone the entire Sourcify repo yourself and serve it using the options, the same way we can serve the rest of the assets locally. For ETH mainnet, it's not too large (few gigabytes total). Maybe once I figure this out myself I can create a writeup.

If you want this privacy today you have to manually go into `src/sourcify/useSourcify.ts` and force `resolveSourcifySource` to return null.

**Comment by wmitsuda** [comment]
There are some docs (a little hidden in the repo) explaining the IPFS usage of Sourcify: https://github.com/wmitsuda/otterscan/blob/develop/docs/ipfs.md

The TLDR is: if you use the IPFS browser plugin, it'll intercept and replace the endpoint, so it doesn't leak info to the default gateway. Ideally, we should use ipfs:// URLs, but it doesn't work on all browsers, so the most portable solution I could think about was the current one.

On that URL you can also find the instructions to pin the Sourcify repo locally (along with lots of tricks you need to pay attention to, it is not so easy, unfortunately).

I'm personally not satisfied with the current solution, still too much friction, open to discuss better UX given the technical limitations imposed by IPFS.

**Comment by sealer3** [comment]
I was thinking that most users of block explorers either don't have an IPFS enabled browser/addon and probably don't have the capacity to host the Sourcify repo locally. A server running Otterscan/Erigon is probably capable of hosting the Sourcify repo itself, and privacy-wise, users already trust the block explorer. So maybe I can find a simple way for the "Sourcify source" to come from a static directory hosted by the server, similar to those in the other assets folder. This would prevent addresses/block explorer usage from being leaked to IPFS nodes, since all the requests go directly to a trusted party and back.

To be honest I don't know enough about IPFS to know if my solution (keeping an entire copy on server) would be problematic with the Sourcify database updating every hour. Maybe the server could request updates for the Sourcify database every so often over IPFS.

The main ask for this issue is to allow Otterscan hosters to specify a custom Sourcify provider in `config.json` if they wish and maybe create some docs for how a server would host the chain-specific Sourcify locally rather than users resolving the Sourcify files over IPFS. I can try to help with both of these whenever I have time since I am the one who wants the behavior.

**Comment by wmitsuda** [comment]
Hm, maybe we could embed a copy of Sourcify repo in the docker image (need to check how big it currently is), so by default we provide a good UX with the DB of verified contracts at build time, if user wants fresher data, then you can configure IPFS stuff.

Last time I checked the entire repo was 17GB (all chains), but mainnet is much smaller, also compression should help, lots of repeating contract text.
