### ISSUE TITLE
Back button history doesn't update when using the search feature

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#671]
When you click links, the back button history is updated allowing you to press the back button to go back. This does not happen when using the search feature.

Steps to reproduce:
1. Navigate to the page of block 1111.
2. Type "1234" into the search bar and press Enter.
3. 1111 does not appear in your history. Pressing the back button will take you back to the page before it (or no page at all if you go directly to `/block/1111`)

It's expected that if you navigate to `/block/1111` and then go to `1234` from the search bar, you can press the back button in the browser to go back to `/block/1111`.

**Comment by wmitsuda** [comment]
yeah, I think it's "replacing page" instead of "navigating to". I don't remember if that was intentional or not (there is another place where I think I made it "replace" on purpose), let me recall I did it that way :)

**Comment by wmitsuda** [comment]
considering as a bug for now :)

**Comment by wmitsuda** [comment]
Merged, thanks!

About my original comment, I think I put replace: true at first to test something, then forgot it, then it replicated by copy/pasting :(
