### ISSUE TITLE
Error thrown when going to address page of transaction hash

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#672]
I typed `/address/0xbac4cb10f95b37dab2c8a78e880d39661cc53f87386ded2fb721ac2304113ea3` into the address bar by mistake instead of `/tx/0xbac4cb10f95b37dab2c8a78e880d39661cc53f87386ded2fb721ac2304113ea3`.

The page is blank accept for the header and footer. There is no error message displayed on the page like the one you get going to `/address/notanaddress`. I sat waiting for a while until I realized the rest of the page wasn't loading.

In the browser console an error is thrown:
```
Error: invalid address (argument="address", value="0xbac4cb10f95b37dab2c8a78e880d39661cc53f87386ded2fb721ac2304113ea3", code=INVALID_ARGUMENT, 
```

The fix is probably simple and related to address parsing.

**Comment by wmitsuda** [comment]
BTW, sorry for the lack of updates, I'm in the middle of a trip/conferences, it's been a little hard to find time/silent place to concentrate on work.

I think the next few days I'll cleanup the issues backlog (or at least answer most of them), but pls keep them coming :)

**Comment by sealer3** [comment]
This issue appears to have been solved. The `AddressOrENSNameNotFound` component renders when you do this now that we use `isAddress` in `useAddressOrENS`.
