### ISSUE TITLE
Hardcoded addresses are not displaying

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#684]
None of the hardcoded addresses in `./src/api/address-resolver/hardcoded-addresses/1.json` are showing for me. The Uniswap and ENS resolvers work just fine.

Could there be something with the uncaught error in HardcodedAddressResolver.ts?

**Comment by sealer3** [comment]
I figured out why. For some reason the HardcodedAddressMap using the `await import ... .json` scheme was actually a module object and not a Record. The Record was available at `(await import ...).default`.

PR incoming

**Comment by wmitsuda** [comment]
This one is very intriguing, I'm pretty sure it worked without the ".default", but now it's broken even in production build.

Spent some hours trying to figure out what led to this regression, but no success. Maybe something during CRA -> vite migration, but I couldn't figure it out.

But, yes, your solution works, I'll merge it.

**Comment by wmitsuda** [comment]
Merged! Thanks for investigating it!
