### ISSUE TITLE
Scaled-down otter image

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#699]
The high quality otter image is great, but we should scale him down on the website since the image dimensions on the home page is 96x96 pixels and 32x32 on the inner pages. The current file size of the image is 1.6 MB, which is large.

128x128 (39.5 KB) or 256x256 (105.2 KB) could be suitable and cut page load time for slow connections on a distribution build.

**Comment by wmitsuda** [comment]
good catch!

**Comment by wmitsuda** [comment]
thanks for the PR, it was a clever solution!
