### ISSUE TITLE
Account transaction count indicator

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#744]
Etherscan displays the number of transactions an account has had above an address's transactions table. This is useful because it tells you how much activity there is. At present, you cannot tell in Otterscan if an address had 30 transactions or 30,000 transactions without going into a recent transaction and looking at the nonce.

So, we should find something to display above the table, maybe to the left of the pagination buttons, that gives an indication of the amount of activity the account has had. One example of this for EOAs might be the account's current transaction count, which is easy to query. Another might be the total number of incoming and outgoing transactions, which is more useful for contracts, which don't send any transactions.

**Comment by wmitsuda** [comment]
Agreed. However that is not possible with current info, i.e., we currently reuse the call from/to indexes from Erigon itself and they don't contain count info.

But that'll be possible with the new indexes we are developing, first for token interactions, if the prototype proves to be successful, then we can apply the same technique to track a count of general address interactions (i.e. regular inbound/outbound state change transactions).

Leaving it opened for now.

**Comment by sealer3** [comment]
I had a feeling it would be difficult based on the transaction page RPC calls. I wonder if in the meantime we can at least say "X outgoing transactions" for EOAs until full indexing is available. This only requires `eth_getTransactionCount`.
