### ISSUE TITLE
Format USD to two decimal places

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#745]
USD values are usually represented to two decimal places. I have noticed that if the second decimal place is a 0, Otterscan formats it to only one decimal place.

See block number 15840000. The Ether price is formatted in Otterscan as `$1,561.4`, but this should be `$1,561.40`.

This also happens in other places where USD values are displayed.

**Comment by wmitsuda** [comment]
Fixed in develop. Pretty sure other places are fixed too, feel free to reopen if you find out any missed case.
