### ISSUE TITLE
Navigation arrows for same-block transactions

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#839]
Otterscan has the very nice feature of navigating to the previous or next transaction from the same sender. There are many times when you want to navigate between different transactions in the same block. For example, maybe you see a pattern of transactions together that you want to observe, like several token mints in a row.

I propose we also include navigation arrows in the Block / Position row, so that we can navigate transactions in sequential order of inclusion in the block.

**Comment by sealer3** [comment]
I think this is a duplicate of #345

**Comment by wmitsuda** [comment]
that's a cool feature, will add to release notes for next release.
