### ISSUE TITLE
Activation Epoch (2^64-1) is still shown for pending_queued validators

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#840]
For validators in the pending_queued state, the beacon node API returns "FAR_FUTURE_EPOCH" = 2^64 - 1 for these validators, and this number is still displayed in Otterscan.

So, we should not display the activation epoch if it has not happened yet. Even better would be to estimate the activation epoch and show a countdown, but I am not sure if we can find the deposit queue size with the current beacon node API.

**Comment by wmitsuda** [comment]
merged into develop, thanks!
