### ISSUE TITLE
Txn tracer: Buffer overrun

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#854]
There is a buffer overrun in the Trace tab for this transaction, causing the entire page to go blank:

0xc859385f19075433cf8671ceff0d3cb3ea0056b30e2f2adcc4cb57df044af48e

In the console:
```
Error: data out-of-bounds (length=41, offset=64, code=BUFFER_OVERRUN, version=abi/5.7.0)
```

**Comment by wmitsuda** [comment]
merged! thanks!
