### ISSUE TITLE
Attestation page creates tens of thousands of requests

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#857]
Viewing any of the page showing the attestations creates tens of thousands of requests.

I tried one time to load a page and after 1 hour it tried to make over 40,000 requests to the beacon node and still never finished loading before I closed the page. It slowed my browser down a lot in the process.

Almost all of these requests are for the state of individual validators. To resolve, we should show the validators on the page without making these requests.

**Comment by wmitsuda** [comment]
Interesting, I had already done a first optimization on attestations page to only render the individual attestation when on display (see `import { useInView } from "react-intersection-observer";`)

Requesting the validators data for the individual attestation is still a lot, much not 40K requests. Which browser?

**Comment by sealer3** [comment]
The browser is Firefox with an HTTP beacon node rpc server. I scrolled to the bottom of the page which didn't help and slowed down my browser. The rpc server is able to deliver responses to me at a rate of about 20-25 requests/sec (non-local).

If we ignore the impact on browser performance, at this rate it would take roughly (64 committees * 256 validators/committee * 1 request/validator * 1 second/25 requests = 655 seconds = 10.92 minutes) to load the page, which is too slow.

Even Beaconcha.in does not show which validators were slashed on the attestations page, so I think it would be okay to show only the validator index and not load all details.

**Comment by sealer3** [comment]
I think the reason over 40,000 requests were issued is that SWR would time out individual requests and resend them, compounding the problem. I think especially at this stage it's unreasonable to have the Otterscan client download what is today over *30,000* validator requests per slot just to show the slashing status of each validator in the attestations tab! What's more, validators which are slashed *cannot attest*, so it is wasteful to make all these requests!

It has been almost a year now, and the Attestations page still crashes my browser. The fix in #889 solves this issue completely.
